export const FETCH_USERS = 'FETCH_USERS';

export const REGISTER_USER = 'REGISTER_USER';
export const REGISTER_USER_SUCCESS = 'REGISTER_USER_SUCCESS';
export const REGISTER_USER_FAILED = 'REGISTER_USER_FAILED';

export const SIGN_IN_USER = 'SIGN_IN_USER';
export const SIGN_IN_USER_SUCCESS = 'SIGN_IN_USER_SUCCESS';
export const SIGN_IN_USER_FAILED = 'SIGN_IN_USER_FAILED';

export const GET_QUIZZES = 'GET_QUIZZES';
export const GET_QUIZZES_SUCCESS = 'GET_QUIZZES_SUCCESS';
export const GET_QUIZZES_FAILED = 'GET_QUIZZES_FAILED';

export const GET_QUIZ_ITEMS = 'GET_QUIZ_ITEMS';
export const GET_QUIZ_ITEMS_SUCCESS = 'GET_QUIZ_ITEMS_SUCCESS';
export const GET_QUIZ_ITEMS_FAILED = 'GET_QUIZ_ITEMS_FAILED';
