export const FETCH_USERS = 'FETCH_USERS';

export const REGISTER_USER = 'REGISTER_USER';
export const REGISTER_USER_SUCCESS = 'REGISTER_USER_SUCCESS';
export const REGISTER_USER_FAILED = 'REGISTER_USER_FAILED';

export const SIGN_IN_USER = 'SIGN_IN_USER';
export const SIGN_IN_USER_SUCCESS = 'SIGN_IN_USER_SUCCESS';
export const SIGN_IN_USER_FAILED = 'SIGN_IN_USER_FAILED';

export const GET_QUIZZES = 'GET_QUIZZES';
export const GET_QUIZZES_SUCCESS = 'GET_QUIZZES_SUCCESS';
export const GET_QUIZZES_FAILED = 'GET_QUIZZES_FAILED';

export const GET_QUIZ_SUMMARIES = 'GET_QUIZ_SUMMARIES';
export const GET_QUIZ_SUMMARIES_SUCCESS = 'GET_QUIZ_SUMMARIES_SUCCESS';
export const GET_QUIZ_SUMMARIES_FAILED = 'GET_QUIZ_SUMMARIES_FAILED';

export const GET_QUIZ_SUMMARY = 'GET_QUIZ_SUMMARY';
export const GET_QUIZ_SUMMARY_SUCCESS = 'GET_QUIZ_SUMMARY_SUCCESS';
export const GET_QUIZ_SUMMARY_FAILED = 'GET_QUIZ_SUMMARY_FAILED';

export const GENERATE_QUIZ_SUMMARY = 'GENERATE_QUIZ_SUMMARY';
export const GENERATE_QUIZ_SUMMARY_SUCCESS = 'GENERATE_QUIZ_SUMMARY_SUCCESS';
export const GENERATE_QUIZ_SUMMARY_FAILED = 'GENERATE_QUIZ_SUMMARY_FAILED';

export const GENERATE_USER_QUIZZES = 'GENERATE_USER_QUIZZES';
export const GENERATE_USER_QUIZZES_SUCCESS = 'GENERATE_USER_QUIZZES_SUCCESS';
export const GENERATE_USER_QUIZZES_FAILED = 'GENERATE_USER_QUIZZES_FAILED';

export const HAS_USER_QUIZ = 'HAS_USER_QUIZ';
export const HAS_USER_QUIZ_SUCCESS = 'HAS_USER_QUIZ_SUCCESS';
export const HAS_USER_QUIZ_FAILED = 'HAS_USER_QUIZ_FAILED';

export const GET_USER_QUIZZES = 'GET_USER_QUIZZES';
export const GET_USER_QUIZZES_SUCCESS = 'GET_USER_QUIZZES_SUCCESS';
export const GET_USER_QUIZZES_FAILED = 'GET_USER_QUIZZES_FAILED';

export const GET_CURRENT_USER_QUIZ = 'GET_CURRENT_USER_QUIZ';
export const GET_CURRENT_USER_QUIZ_SUCCESS = 'GET_CURRENT_USER_QUIZ_SUCCESS';
export const GET_CURRENT_USER_QUIZ_FAILED = 'GET_CURRENT_USER_QUIZ_FAILED';

export const GET_USER_QUIZ_ITEMS = 'GET_USER_QUIZ_ITEMS';
export const GET_USER_QUIZ_ITEMS_SUCCESS = 'GET_USER_QUIZ_ITEMS_SUCCESS';
export const GET_USER_QUIZ_ITEMS_FAILED = 'GET_USER_QUIZ_ITEMS_FAILED';

export const UPDATE_USER_QUIZ_ANSWER = 'UPDATE_USER_QUIZ_ANSWER';
export const UPDATE_USER_QUIZ_ANSWER_SUCCESS = 'UPDATE_USER_QUIZ_ANSWER_SUCCESS';
export const UPDATE_USER_QUIZ_ANSWER_FAILED = 'UPDATE_USER_QUIZ_ANSWER_FAILED';
